spring:
  application:
    name: bpmn-diff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/bpmn-diff

server:
  port: 9000

frontend:
  url: http://localhost:5173